# Generated by Django 5.1.1 on 2024-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0002_member_borrowings_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='borrower_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
