# Generated by Django 5.1.1 on 2024-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0003_alter_media_borrower_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='borrower_number',
            new_name='borrowers_number',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='borrowings_numbers',
            new_name='borrowings_number',
        ),
        migrations.RemoveField(
            model_name='media',
            name='borrower_member',
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(default='Default Type', max_length=15),
        ),
        migrations.AlterField(
            model_name='media',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
