# Generated by Django 5.1.1 on 2024-10-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0004_rename_borrower_number_media_borrowers_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarians.media')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarians.member')),
            ],
        ),
    ]
