# Generated by Django 5.1.1 on 2024-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0005_borrowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='media',
            name='borrowing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
