# Generated by Django 5.1.1 on 2024-10-26 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0006_alter_borrowing_options_alter_media_borrowing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 11, 2)),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_date',
            field=models.DateField(default=datetime.date(2024, 10, 26)),
        ),
    ]
