# Generated by Django 5.1.1 on 2024-10-26 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0007_borrowing_due_date_alter_borrowing_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
