# Generated by Django 5.1.1 on 2024-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0010_borrowing_content_type_borrowing_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowers_number',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='borrowers_number',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='borrowers_number',
        ),
        migrations.AddField(
            model_name='board_game',
            name='borrowing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
