# Generated by Django 5.1.1 on 2024-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0011_remove_book_borrowers_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borrowings_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
