# Generated by Django 5.1.1 on 2024-11-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0012_alter_member_borrowings_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_game',
            name='borrowing_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowing_date',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='borrowing_date',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='borrowing_date',
        ),
    ]
